import { analyticsRepository } from "@/src/server/repositories/analytics-repository";
import { adsRepository } from "@/src/server/repositories/ads-repository";
import { eventRepository } from "@/src/server/repositories/event-repository";
import { historicalAuthorityRepository } from "@/src/server/repositories/historical-authority-repository";
import { governanceService } from "@/src/server/services/governance-service";
import { governanceOperationsService } from "@/src/server/services/governance-operations-service";
import { historicalLibraryService } from "@/src/server/services/historical-library-service";
import { publishedMemoryProjectionService } from "@/src/server/services/published-memory-projection-service";
import { factoryService } from "@/src/server/services/factory-service";
import { requestRepository } from "@/src/server/repositories/request-repository";
import { tagRepository } from "@/src/server/repositories/tag-repository";
import { taxonomyRepository } from "@/src/server/repositories/taxonomy-repository";
import { timelineRepository } from "@/src/server/repositories/timeline-repository";
import { relationshipRecoveryService } from "@/src/server/services/relationship-recovery-service";

export const adminService = {
  getDashboardOverview: analyticsRepository.getDashboardOverview,
  getAnalyticsSnapshot: analyticsRepository.getAnalyticsSnapshot,
  getAnalyticsReport: analyticsRepository.getAnalyticsReport,
  listTimelines: () => timelineRepository.listSummaries(100),
  exportTimelinesRegistry: timelineRepository.listRegistryExport,
  getTimelineById: timelineRepository.getById,
  createTimeline: timelineRepository.create,
  updateTimeline: timelineRepository.update,
  deleteTimeline: timelineRepository.delete,
  listEvents: eventRepository.list,
  createEvent: eventRepository.create,
  updateEvent: eventRepository.update,
  deleteEvent: eventRepository.delete,
  listTags: tagRepository.list,
  getTaxonomyGovernanceSnapshot: taxonomyRepository.getGovernanceSnapshot,
  getHistoricalAuthoritySnapshot: historicalAuthorityRepository.getSnapshot,
  getGovernanceOperationsSnapshot: governanceOperationsService.getSnapshot,
  rebuildPublishedMemoryProjections: publishedMemoryProjectionService.rebuildAll,
  createGovernanceDecision: governanceService.createDecision,
  createGovernanceApproval: governanceService.createApproval,
  createGovernanceQueue: governanceService.createQueue,
  createPublicationPackage: governanceService.createPublicationPackage,
  createFeedbackPackage: governanceService.createFeedbackPackage,
  createGovernanceDispute: governanceService.createDispute,
  createGovernanceAuditRecord: governanceService.createAuditRecord,
  submitGovernanceDecision: governanceService.submitDecision,
  reviewGovernanceDecision: governanceService.reviewDecision,
  approveGovernanceDecision: governanceService.approveDecision,
  rejectGovernanceDecision: governanceService.rejectDecision,
  escalateGovernanceDecision: governanceService.escalateDecision,
  supersedeGovernanceDecision: governanceService.supersedeDecision,
  approveGovernanceApprovalStep: governanceService.approveStep,
  rejectGovernanceApprovalStep: governanceService.rejectStep,
  completeGovernanceApprovalChain: governanceService.completeApprovalChain,
  advanceGovernanceQueue: governanceService.advanceQueue,
  escalateGovernanceQueue: governanceService.escalateQueue,
  certifyPublicationReadiness: governanceService.certifyReadiness,
  acceptPublicationPackage: governanceService.acceptPackage,
  rejectPublicationPackage: governanceService.rejectPackage,
  returnPublicationPackage: governanceService.returnPackage,
  publishPublicationPackage: governanceService.publishPackage,
  acknowledgeFeedbackPackage: governanceService.acknowledgeFeedback,
  resolveFeedbackPackage: governanceService.resolveFeedback,
  closeFeedbackPackage: governanceService.closeFeedback,
  triageGovernanceDispute: governanceService.triageDispute,
  escalateGovernanceDispute: governanceService.escalateDispute,
  resolveGovernanceDispute: governanceService.resolveDispute,
  closeGovernanceDispute: governanceService.closeDispute,
  admitPublicationPackageToHistoricalLibrary: historicalLibraryService.admitPublicationPackage,
  revisePublishedMemory: historicalLibraryService.revisePublishedMemory,
  retirePublishedMemory: historicalLibraryService.retirePublishedMemory,
  mergePublishedMemory: historicalLibraryService.mergePublishedMemory,
  preservePublishedMemory: historicalLibraryService.preservePublishedMemory,
  generateHistoricalLibraryFeedbackPackage: historicalLibraryService.generateFeedbackPackage,
  createFactoryObject: factoryService.createObject,
  transitionFactoryObject: factoryService.transitionObject,
  createFactoryArtifact: factoryService.createArtifact,
  createFactoryPackageDraft: factoryService.createPackageDraft,
  transitionFactoryPackageDraft: factoryService.transitionPackageDraft,
  createFactoryPackageVersion: factoryService.createPackageVersion,
  markFactoryPackageVersionSubmitted: factoryService.markPackageVersionSubmitted,
  intakeFactoryFeedback: factoryService.intakeFeedbackPackage,
  transitionFactoryFeedback: factoryService.transitionFeedbackConsumption,
  createFactoryRevisionPlan: factoryService.createRevisionPlan,
  prepareFactoryResubmission: factoryService.prepareResubmission,
  completeFactoryResubmission: factoryService.completeResubmission,
  createHistoricalObject: historicalAuthorityRepository.createObject,
  reviseHistoricalObject: historicalAuthorityRepository.reviseObject,
  mergeHistoricalObject: historicalAuthorityRepository.mergeObject,
  retireHistoricalObject: historicalAuthorityRepository.retireObject,
  createMilestoneParticipation: historicalAuthorityRepository.createParticipation,
  reviseMilestoneParticipation: historicalAuthorityRepository.reviseParticipation,
  disputeMilestoneParticipation: historicalAuthorityRepository.disputeParticipation,
  retireMilestoneParticipation: historicalAuthorityRepository.retireParticipation,
  createTag: tagRepository.create,
  updateTag: tagRepository.update,
  deleteTag: tagRepository.delete,
  listRequests: requestRepository.list,
  updateRequestStatus: requestRepository.updateStatus,
  getAdsDashboardData: adsRepository.getDashboardData,
  createAdCampaign: adsRepository.createCampaign,
  updateAdCampaign: adsRepository.updateCampaign,
  deleteAdCampaign: adsRepository.deleteCampaign,
  previewRelationshipRecovery: relationshipRecoveryService.preview,
  applyRelationshipRecovery: relationshipRecoveryService.apply,
  listRelationshipRecoveryReports: relationshipRecoveryService.listReports,
  getRelationshipRecoveryReport: relationshipRecoveryService.getReport,
  exportRelationshipRecoveryReportCsv: relationshipRecoveryService.reportToCsv
};
