import { analyticsRepository } from "@/src/server/repositories/analytics-repository";
import { adsRepository } from "@/src/server/repositories/ads-repository";
import { eventRepository } from "@/src/server/repositories/event-repository";
import { historicalAuthorityRepository } from "@/src/server/repositories/historical-authority-repository";
import { historicalRelationshipRepository } from "@/src/server/repositories/historical-relationship-repository";
import { governanceService } from "@/src/server/services/governance-service";
import { governanceOperationsService } from "@/src/server/services/governance-operations-service";
import { historicalLibraryService } from "@/src/server/services/historical-library-service";
import { publishedMemoryProjectionService } from "@/src/server/services/published-memory-projection-service";
import { factoryService } from "@/src/server/services/factory-service";
import { requestRepository } from "@/src/server/repositories/request-repository";
import { tagRepository } from "@/src/server/repositories/tag-repository";
import { taxonomyRepository } from "@/src/server/repositories/taxonomy-repository";
import { timelineRepository } from "@/src/server/repositories/timeline-repository";
import { relationshipRecoveryService } from "@/src/server/services/relationship-recovery-service";

export const adminService = {
  getDashboardOverview: analyticsRepository.getDashboardOverview,
  getAnalyticsSnapshot: analyticsRepository.getAnalyticsSnapshot,
  getAnalyticsReport: analyticsRepository.getAnalyticsReport,
  listTimelines: () => timelineRepository.listSummaries(100),
  exportTimelinesRegistry: timelineRepository.listRegistryExport,
  getTimelineById: timelineRepository.getById,
  createTimeline: timelineRepository.create,
  updateTimeline: timelineRepository.update,
  deleteTimeline: timelineRepository.delete,
  listEvents: eventRepository.list,
  createEvent: eventRepository.create,
  updateEvent: eventRepository.update,
  deleteEvent: eventRepository.delete,
  listTags: tagRepository.list,
  getTaxonomyGovernanceSnapshot: taxonomyRepository.getGovernanceSnapshot,
  getHistoricalAuthoritySnapshot: historicalAuthorityRepository.getSnapshot,
  getGovernanceOperationsSnapshot: governanceOperationsService.getSnapshot,
  rebuildPublishedMemoryProjections: publishedMemoryProjectionService.rebuildAll,
  getPublishedMemoryProjectionCutoverMetrics: publishedMemoryProjectionService.getCutoverMetrics,
  createGovernanceDecision: governanceService.createDecision,
  createGovernanceApproval: governanceService.createApproval,
  createGovernanceQueue: governanceService.createQueue,
  createPublicationPackage: governanceService.createPublicationPackage,
  createFeedbackPackage: governanceService.createFeedbackPackage,
  createGovernanceDispute: governanceService.createDispute,
  createGovernanceAuditRecord: governanceService.createAuditRecord,
  submitGovernanceDecision: governanceService.submitDecision,
  reviewGovernanceDecision: governanceService.reviewDecision,
  approveGovernanceDecision: governanceService.approveDecision,
  rejectGovernanceDecision: governanceService.rejectDecision,
  escalateGovernanceDecision: governanceService.escalateDecision,
  supersedeGovernanceDecision: governanceService.supersedeDecision,
  approveGovernanceApprovalStep: governanceService.approveStep,
  rejectGovernanceApprovalStep: governanceService.rejectStep,
  completeGovernanceApprovalChain: governanceService.completeApprovalChain,
  advanceGovernanceQueue: governanceService.advanceQueue,
  escalateGovernanceQueue: governanceService.escalateQueue,
  submitPublicationPackageToGovernanceReview: governanceService.submitPackage,
  certifyPublicationReadiness: governanceService.certifyReadiness,
  submitPublicationPackageToLibraryReview: governanceService.submitPackageToLibraryReview,
  acceptPublicationPackage: governanceService.acceptPackage,
  rejectPublicationPackage: governanceService.rejectPackage,
  returnPublicationPackage: governanceService.returnPackage,
  publishPublicationPackage: governanceService.publishPackage,
  acknowledgeFeedbackPackage: governanceService.acknowledgeFeedback,
  resolveFeedbackPackage: governanceService.resolveFeedback,
  closeFeedbackPackage: governanceService.closeFeedback,
  triageGovernanceDispute: governanceService.triageDispute,
  escalateGovernanceDispute: governanceService.escalateDispute,
  resolveGovernanceDispute: governanceService.resolveDispute,
  closeGovernanceDispute: governanceService.closeDispute,
  admitPublicationPackageToHistoricalLibrary: historicalLibraryService.admitPublicationPackage,
  revisePublishedMemory: historicalLibraryService.revisePublishedMemory,
  retirePublishedMemory: historicalLibraryService.retirePublishedMemory,
  mergePublishedMemory: historicalLibraryService.mergePublishedMemory,
  preservePublishedMemory: historicalLibraryService.preservePublishedMemory,
  generateHistoricalLibraryFeedbackPackage: historicalLibraryService.generateFeedbackPackage,
  createFactoryObject: factoryService.createObject,
  transitionFactoryObject: factoryService.transitionObject,
  createFactoryArtifact: factoryService.createArtifact,
  createFactoryPackageDraft: factoryService.createPackageDraft,
  transitionFactoryPackageDraft: factoryService.transitionPackageDraft,
  createFactoryPackageVersion: factoryService.createPackageVersion,
  markFactoryPackageVersionSubmitted: factoryService.markPackageVersionSubmitted,
  intakeFactoryFeedback: factoryService.intakeFeedbackPackage,
  transitionFactoryFeedback: factoryService.transitionFeedbackConsumption,
  createFactoryRevisionPlan: factoryService.createRevisionPlan,
  prepareFactoryResubmission: factoryService.prepareResubmission,
  completeFactoryResubmission: factoryService.completeResubmission,
  registerFactoryRuntimeWorker: factoryService.registerRuntimeWorker,
  listFactoryRuntimeWorkers: factoryService.listRuntimeWorkers,
  registerFactoryRuntimePrompt: factoryService.registerRuntimePrompt,
  listFactoryRuntimePrompts: factoryService.listRuntimePrompts,
  queueFactoryRuntimeJob: factoryService.queueRuntimeJob,
  listFactoryRuntimeJobs: factoryService.listRuntimeJobs,
  transitionFactoryRuntimeJob: factoryService.transitionRuntimeJob,
  executeFactoryRuntimeJob: factoryService.executeRuntimeJob,
  listFactoryRuntimeExecutions: factoryService.listRuntimeExecutions,
  getFactoryRuntimeMetrics: factoryService.getRuntimeMetrics,
  getFactoryRuntimeHealth: factoryService.getRuntimeHealth,
  syncFactoryWorkerRegistry: factoryService.syncCanonicalWorkerRegistry,
  listFactoryWorkerRegistry: factoryService.listWorkerRegistry,
  listFactoryPipelineDefinitions: factoryService.listPipelineDefinitions,
  startFactoryPipeline: factoryService.startPipeline,
  listFactoryPipelineRuns: factoryService.listPipelineRuns,
  cancelFactoryPipeline: factoryService.cancelPipeline,
  prepareFactoryGovernanceHandoff: factoryService.prepareGovernanceHandoff,
  submitFactoryGovernanceHandoff: factoryService.submitToGovernance,
  getFactoryGovernanceHandoffStatus: factoryService.getHandoffStatus,
  listFactoryGovernanceSubmissions: factoryService.listGovernanceSubmissions,
  validateCandidatePackage: factoryService.validateCandidatePackage,
  reviewCandidatePackage: factoryService.reviewCandidatePackage,
  approveEditorialReview: factoryService.approveEditorialReview,
  requireFactoryEditorialRevision: factoryService.requireRevision,
  prepareFactoryAuthorityRecords: factoryService.prepareAuthorityRecords,
  assessFactoryGovernanceReadiness: factoryService.assessGovernanceReadiness,
  listFactoryEditorialReviews: factoryService.listEditorialReviews,
  getFactoryEditorialReview: factoryService.getEditorialReview,
  discoverFactoryExternalSources: factoryService.discoverExternalSources,
  retrieveFactoryExternalSource: factoryService.retrieveExternalSource,
  generateFactoryCorpusDocument: factoryService.generateCorpusDocument,
  extractFactoryEvidenceRecords: factoryService.extractEvidenceRecords,
  validateFactoryEvidenceRecord: factoryService.validateEvidenceRecord,
  createHistoricalObject: historicalAuthorityRepository.createObject,
  reviseHistoricalObject: historicalAuthorityRepository.reviseObject,
  mergeHistoricalObject: historicalAuthorityRepository.mergeObject,
  retireHistoricalObject: historicalAuthorityRepository.retireObject,
  createMilestoneParticipation: historicalAuthorityRepository.createParticipation,
  reviseMilestoneParticipation: historicalAuthorityRepository.reviseParticipation,
  disputeMilestoneParticipation: historicalAuthorityRepository.disputeParticipation,
  retireMilestoneParticipation: historicalAuthorityRepository.retireParticipation,
  listHistoricalRelationships: historicalRelationshipRepository.list,
  createHistoricalRelationship: historicalRelationshipRepository.create,
  reviseHistoricalRelationship: historicalRelationshipRepository.revise,
  disputeHistoricalRelationship: historicalRelationshipRepository.dispute,
  retireHistoricalRelationship: historicalRelationshipRepository.retire,
  mergeHistoricalRelationship: historicalRelationshipRepository.merge,
  preserveHistoricalRelationship: historicalRelationshipRepository.preserve,
  createTag: tagRepository.create,
  updateTag: tagRepository.update,
  deleteTag: tagRepository.delete,
  listRequests: requestRepository.list,
  updateRequestStatus: requestRepository.updateStatus,
  getAdsDashboardData: adsRepository.getDashboardData,
  createAdCampaign: adsRepository.createCampaign,
  updateAdCampaign: adsRepository.updateCampaign,
  deleteAdCampaign: adsRepository.deleteCampaign,
  previewRelationshipRecovery: relationshipRecoveryService.preview,
  applyRelationshipRecovery: relationshipRecoveryService.apply,
  listRelationshipRecoveryReports: relationshipRecoveryService.listReports,
  getRelationshipRecoveryReport: relationshipRecoveryService.getReport,
  exportRelationshipRecoveryReportCsv: relationshipRecoveryService.reportToCsv
};
