DROP TRIGGER IF EXISTS prevent_sr_cert_invariant_results_mut ON search_certification_invariant_results;
DROP TRIGGER IF EXISTS prevent_sr_cert_failure_results_mut ON search_certification_failure_results;
DROP TRIGGER IF EXISTS prevent_sr_cert_search_results_mut ON search_certification_search_results;
DROP TRIGGER IF EXISTS prevent_sr_cert_case_results_mut ON search_certification_case_results;
DROP TRIGGER IF EXISTS prevent_sr_cert_stage_results_mut ON search_certification_stage_results;
DROP TRIGGER IF EXISTS prevent_sr_cert_runs_mut ON search_certification_runs;

DROP TABLE IF EXISTS search_certification_invariant_results;
DROP TABLE IF EXISTS search_certification_failure_results;
DROP TABLE IF EXISTS search_certification_search_results;
DROP TABLE IF EXISTS search_certification_case_results;
DROP TABLE IF EXISTS search_certification_stage_results;
DROP TABLE IF EXISTS search_certification_runs;

DROP FUNCTION IF EXISTS prevent_search_certification_mutation();
